### ISSUE TITLE
Add calculator

### ISSUE THREAD

**Issue by pavithra-064** [HarryPoter0/Front-end_Development#18]
Hey I would like to do a calculator using HTML,CSS and JS , could you assign me this under Hacktoberfest , so that I can make a PR soon. Thanks in advance.

**Comment by HarryPoter0** [comment]
You can make pull request. Thanks.

**Comment by krishnabiradar310802** [comment]
Can i work on this?

**Comment by pavithra-064** [comment]
> Can i work on this?

I am already working on this

**Comment by krishnabiradar310802** [comment]
@pavithra-064 ya so many people can work on the same issue and who ever does it first takes the merge

**Comment by HarryPoter0** [comment]
Merged!!
